import { db } from './db';
import { categories, products, reviews, users } from '@shared/schema';
import { seedTestAccounts } from './test-accounts-seed';

export async function seedDatabase() {
  try {
    console.log('🌱 Starting database seeding...');

    // Clear existing data
    await db.delete(reviews);
    await db.delete(products);
    await db.delete(categories);
    
    // Create seed users for reviews
    const seedUsers = [
      {
        id: 'seed-user-1',
        email: 'nguyen.minh@gmail.com',
        firstName: 'Minh',
        lastName: 'Nguyen',
        profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-2',
        email: 'sarah.johnson@outlook.com',
        firstName: 'Sarah',
        lastName: 'Johnson',
        profileImageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b6c5b5a5?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-3',
        email: 'kim.hyun@naver.com',
        firstName: 'Hyun',
        lastName: 'Kim',
        profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-4',
        email: 'alexei.petrov@yandex.ru',
        firstName: 'Alexei',
        lastName: 'Petrov',
        profileImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-5',
        email: 'tran.linh@yahoo.com',
        firstName: 'Linh',
        lastName: 'Tran',
        profileImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-6',
        email: 'james.williams@gmail.com',
        firstName: 'James',
        lastName: 'Williams',
        profileImageUrl: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-7',
        email: 'hoang.thu@gmail.com',
        firstName: 'Thu',
        lastName: 'Hoang',
        profileImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-8',
        email: 'duc.pham@hotmail.com',
        firstName: 'Duc',
        lastName: 'Pham',
        profileImageUrl: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-9',
        email: 'lee.soo@gmail.com',
        firstName: 'Soo Jin',
        lastName: 'Lee',
        profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-10',
        email: 'maria.rodriguez@gmail.com',
        firstName: 'Maria',
        lastName: 'Rodriguez',
        profileImageUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-11',
        email: 'an.nguyen@gmail.com',
        firstName: 'An',
        lastName: 'Nguyen',
        profileImageUrl: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-12',
        email: 'david.chen@yahoo.com',
        firstName: 'David',
        lastName: 'Chen',
        profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-13',
        email: 'thuy.le@outlook.com',
        firstName: 'Thuy',
        lastName: 'Le',
        profileImageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b6c5b5a5?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-14',
        email: 'cuong.vu@gmail.com',
        firstName: 'Cuong',
        lastName: 'Vu',
        profileImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-15',
        email: 'michael.brown@gmail.com',
        firstName: 'Michael',
        lastName: 'Brown',
        profileImageUrl: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-16',
        email: 'emily.davis@gmail.com',
        firstName: 'Emily',
        lastName: 'Davis',
        profileImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
      },
      {
        id: 'seed-user-17',
        email: 'park.min@naver.com',
        firstName: 'Min Ho',
        lastName: 'Park',
        profileImageUrl: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&h=100&fit=crop&crop=face',
      },
    ];

    await db.insert(users).values(seedUsers).onConflictDoNothing();

    // Insert categories
    const categoryData = [
      {
        name: 'Electronics',
        description: 'Latest gadgets and electronic devices',
        slug: 'electronics',
        imageUrl: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=500&h=300&fit=crop',
      },
      {
        name: 'Fashion',
        description: 'Trendy clothing and accessories',
        slug: 'fashion',
        imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500&h=300&fit=crop',
      },
      {
        name: 'Home & Garden',
        description: 'Everything for your home and garden',
        slug: 'home-garden',
        imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=300&fit=crop',
      },
      {
        name: 'Sports & Outdoors',
        description: 'Sports equipment and outdoor gear',
        slug: 'sports',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=300&fit=crop',
      },
      {
        name: 'Books & Media',
        description: 'Books, movies, and educational content',
        slug: 'books',
        imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=300&fit=crop',
      },
      {
        name: 'Health & Beauty',
        description: 'Health, beauty, and personal care products',
        slug: 'health-beauty',
        imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=300&fit=crop',
      },
      {
        name: 'Automotive',
        description: 'Car accessories and automotive parts',
        slug: 'automotive',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=500&h=300&fit=crop',
      },
      {
        name: 'Toys & Games',
        description: 'Fun toys and games for all ages',
        slug: 'toys-games',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=300&fit=crop',
      },
      {
        name: 'Pet Supplies',
        description: 'Everything for your furry friends',
        slug: 'pet-supplies',
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&h=300&fit=crop',
      },
      {
        name: 'Food & Beverages',
        description: 'Gourmet food and specialty beverages',
        slug: 'food-beverages',
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=300&fit=crop',
      },
      {
        name: 'Vietnamese Specialties',
        description: 'Authentic Vietnamese products and local crafts',
        slug: 'vietnamese-specialties',
        imageUrl: 'https://images.unsplash.com/photo-1559301504-b64d56861fbe?w=500&h=300&fit=crop',
      },
      {
        name: 'Office & Business',
        description: 'Office supplies and business equipment',
        slug: 'office-business',
        imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=500&h=300&fit=crop',
      },
      {
        name: 'Art & Crafts',
        description: 'Creative supplies and handmade crafts',
        slug: 'art-crafts',
        imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500&h=300&fit=crop',
      },
    ];

    const insertedCategories = await db.insert(categories).values(categoryData).returning();
    console.log(`✅ Created ${insertedCategories.length} categories`);

    // Insert products
    const productData = [
      // Electronics
      {
        title: 'iPhone 15 Pro Max',
        description: 'Latest iPhone with titanium design, A17 Pro chip, and advanced camera system. Perfect for photography enthusiasts and professionals.',
        price: 1199.99,
        stock: 25,
        categoryId: insertedCategories[0].id,
        sellerId: 'seed-seller-1',
        imageUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 147,
      },
      {
        title: 'Samsung Galaxy S24 Ultra',
        description: 'Premium Android smartphone with S Pen, 200MP camera, and AI-powered features. Built for productivity and creativity.',
        price: 1299.99,
        stock: 18,
        categoryId: insertedCategories[0].id,
        sellerId: 'seed-seller-2',
        imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 89,
      },
      {
        title: 'MacBook Pro 14" M3',
        description: 'Powerful laptop with M3 chip, Liquid Retina XDR display, and all-day battery life. Ideal for professionals and creators.',
        price: 1999.99,
        stock: 12,
        categoryId: insertedCategories[0].id,
        sellerId: 'seed-seller-1',
        imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.9,
        reviewCount: 203,
      },
      {
        title: 'Sony WH-1000XM5 Headphones',
        description: 'Industry-leading noise canceling wireless headphones with premium sound quality and 30-hour battery life.',
        price: 399.99,
        stock: 45,
        categoryId: insertedCategories[0].id,
        sellerId: 'seed-seller-3',
        imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 312,
      },
      {
        title: 'Nintendo Switch OLED',
        description: 'Handheld gaming console with vibrant OLED screen, enhanced audio, and versatile gameplay modes.',
        price: 349.99,
        stock: 32,
        categoryId: insertedCategories[0].id,
        sellerId: 'seed-seller-2',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.5,
        reviewCount: 156,
      },

      // Fashion
      {
        title: 'Levi\'s 501 Original Jeans',
        description: 'Classic straight-leg jeans with authentic fit and timeless style. Made from premium denim for durability and comfort.',
        price: 89.99,
        stock: 67,
        categoryId: insertedCategories[1].id,
        sellerId: 'seed-seller-4',
        imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.4,
        reviewCount: 89,
      },
      {
        title: 'Nike Air Max 270',
        description: 'Comfortable lifestyle sneakers with Max Air unit for exceptional cushioning and modern design.',
        price: 149.99,
        stock: 89,
        categoryId: insertedCategories[1].id,
        sellerId: 'seed-seller-5',
        imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.3,
        reviewCount: 234,
      },
      {
        title: 'Cashmere Blend Sweater',
        description: 'Luxurious cashmere blend sweater with soft texture and elegant design. Perfect for professional and casual settings.',
        price: 129.99,
        stock: 34,
        categoryId: insertedCategories[1].id,
        sellerId: 'seed-seller-4',
        imageUrl: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 67,
      },
      {
        title: 'Leather Crossbody Bag',
        description: 'Genuine leather crossbody bag with adjustable strap and multiple compartments. Stylish and functional.',
        price: 199.99,
        stock: 23,
        categoryId: insertedCategories[1].id,
        sellerId: 'seed-seller-6',
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 145,
      },

      // Home & Garden
      {
        title: 'Instant Pot Duo 7-in-1',
        description: 'Multi-functional electric pressure cooker that replaces 7 kitchen appliances. Perfect for quick and healthy meals.',
        price: 99.99,
        stock: 56,
        categoryId: insertedCategories[2].id,
        sellerId: 'seed-seller-7',
        imageUrl: 'https://images.unsplash.com/photo-1585515656973-e8073b938cb8?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 892,
      },
      {
        title: 'Dyson V15 Detect Vacuum',
        description: 'Cordless vacuum with laser dust detection and powerful suction. Advanced cleaning technology for all floor types.',
        price: 749.99,
        stock: 18,
        categoryId: insertedCategories[2].id,
        sellerId: 'seed-seller-8',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.9,
        reviewCount: 234,
      },
      {
        title: 'Philips Hue Smart Bulbs 4-Pack',
        description: 'Color-changing smart LED bulbs with app control and voice activation. Create the perfect ambiance for any occasion.',
        price: 199.99,
        stock: 78,
        categoryId: insertedCategories[2].id,
        sellerId: 'seed-seller-7',
        imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.5,
        reviewCount: 167,
      },

      // Sports & Outdoors
      {
        title: 'Peloton Bike+',
        description: 'Premium indoor cycling bike with rotating touchscreen and live classes. Transform your home into a fitness studio.',
        price: 2495.00,
        stock: 8,
        categoryId: insertedCategories[3].id,
        sellerId: 'seed-seller-9',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.4,
        reviewCount: 78,
      },
      {
        title: 'Hydro Flask Water Bottle',
        description: 'Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours. Perfect for active lifestyles.',
        price: 44.99,
        stock: 124,
        categoryId: insertedCategories[3].id,
        sellerId: 'seed-seller-10',
        imageUrl: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 456,
      },
      {
        title: 'Adidas Ultraboost 22',
        description: 'High-performance running shoes with responsive cushioning and energy return. Designed for serious runners.',
        price: 189.99,
        stock: 67,
        categoryId: insertedCategories[3].id,
        sellerId: 'seed-seller-11',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 234,
      },

      // Books & Media
      {
        title: 'The Psychology of Money',
        description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel. Essential reading for financial literacy.',
        price: 16.99,
        stock: 145,
        categoryId: insertedCategories[4].id,
        sellerId: 'seed-seller-12',
        imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 1234,
      },
      {
        title: 'Atomic Habits',
        description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear. Transform your life with small changes.',
        price: 18.99,
        stock: 89,
        categoryId: insertedCategories[4].id,
        sellerId: 'seed-seller-12',
        imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.9,
        reviewCount: 2156,
      },

      // Health & Beauty
      {
        title: 'Cetaphil Gentle Skin Cleanser',
        description: 'Gentle, non-irritating cleanser for sensitive skin. Fragrance-free and recommended by dermatologists.',
        price: 14.99,
        stock: 234,
        categoryId: insertedCategories[5].id,
        sellerId: 'seed-seller-13',
        imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.5,
        reviewCount: 567,
      },
      {
        title: 'Olaplex Hair Perfector No. 3',
        description: 'At-home hair treatment that reduces breakage and strengthens hair. Works on all hair types.',
        price: 28.99,
        stock: 156,
        categoryId: insertedCategories[5].id,
        sellerId: 'seed-seller-14',
        imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 789,
      },

      // Automotive
      {
        title: 'Dash Cam 4K Front and Rear',
        description: 'High-resolution dash camera with night vision, GPS, and collision detection. Essential for safe driving.',
        price: 159.99,
        stock: 45,
        categoryId: insertedCategories[6].id,
        sellerId: 'seed-seller-15',
        imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.4,
        reviewCount: 234,
      },
      {
        title: 'Tire Pressure Monitor System',
        description: 'Wireless TPMS with LCD display and real-time alerts. Monitor all four tires simultaneously.',
        price: 89.99,
        stock: 67,
        categoryId: insertedCategories[6].id,
        sellerId: 'seed-seller-16',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.2,
        reviewCount: 156,
      },
      {
        title: 'Car Phone Mount Wireless Charger',
        description: 'Magnetic wireless charging car mount with automatic clamping. Compatible with all Qi-enabled devices.',
        price: 49.99,
        stock: 89,
        categoryId: insertedCategories[6].id,
        sellerId: 'seed-seller-15',
        imageUrl: 'https://images.unsplash.com/photo-1502877828070-33b88ca48a42?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.5,
        reviewCount: 345,
      },

      // Toys & Games
      {
        title: 'LEGO Architecture Statue of Liberty',
        description: 'Detailed LEGO model of the iconic Statue of Liberty. Perfect for display and educational fun.',
        price: 99.99,
        stock: 34,
        categoryId: insertedCategories[7].id,
        sellerId: 'seed-seller-17',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 123,
      },
      {
        title: 'Ravensburger 1000 Piece Puzzle',
        description: 'Premium quality jigsaw puzzle with vibrant colors and precision-cut pieces. Great for family time.',
        price: 19.99,
        stock: 78,
        categoryId: insertedCategories[7].id,
        sellerId: 'seed-seller-18',
        imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 567,
      },
      {
        title: 'Monopoly Classic Board Game',
        description: 'The classic property trading game for 2-6 players. Hours of family entertainment.',
        price: 24.99,
        stock: 56,
        categoryId: insertedCategories[7].id,
        sellerId: 'seed-seller-17',
        imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.3,
        reviewCount: 234,
      },

      // Pet Supplies
      {
        title: 'Automatic Pet Feeder with Camera',
        description: 'Smart pet feeder with HD camera, two-way audio, and scheduled feeding. Monitor your pet remotely.',
        price: 129.99,
        stock: 23,
        categoryId: insertedCategories[8].id,
        sellerId: 'seed-seller-19',
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 189,
      },
      {
        title: 'Orthopedic Dog Bed Large',
        description: 'Memory foam dog bed with removable washable cover. Provides superior comfort for senior dogs.',
        price: 79.99,
        stock: 45,
        categoryId: insertedCategories[8].id,
        sellerId: 'seed-seller-20',
        imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 456,
      },
      {
        title: 'Interactive Cat Laser Toy',
        description: 'Automatic laser toy that keeps cats entertained for hours. Random patterns and timer settings.',
        price: 39.99,
        stock: 67,
        categoryId: insertedCategories[8].id,
        sellerId: 'seed-seller-19',
        imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.4,
        reviewCount: 234,
      },

      // Food & Beverages
      {
        title: 'Organic Vietnamese Coffee Beans',
        description: 'Premium single-origin coffee beans from Vietnamese highlands. Rich, bold flavor with chocolate notes.',
        price: 34.99,
        stock: 89,
        categoryId: insertedCategories[9].id,
        sellerId: 'seed-seller-21',
        imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.9,
        reviewCount: 345,
      },
      {
        title: 'Gourmet Chocolate Gift Set',
        description: 'Assorted premium chocolates from around the world. Perfect for special occasions and gifts.',
        price: 49.99,
        stock: 34,
        categoryId: insertedCategories[9].id,
        sellerId: 'seed-seller-22',
        imageUrl: 'https://images.unsplash.com/photo-1549398240-0d2c8fc7ce75?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 567,
      },
      {
        title: 'Organic Matcha Green Tea Powder',
        description: 'Ceremonial grade matcha powder from Japan. Rich in antioxidants and perfect for tea ceremonies.',
        price: 24.99,
        stock: 56,
        categoryId: insertedCategories[9].id,
        sellerId: 'seed-seller-23',
        imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 234,
      },

      // Vietnamese Specialties
      {
        title: 'Áo Dài Traditional Vietnamese Dress',
        description: 'Authentic Vietnamese Áo Dài with beautiful silk fabric and traditional embroidery. Perfect for special occasions.',
        price: 199.99,
        stock: 15,
        categoryId: insertedCategories[10].id,
        sellerId: 'seed-seller-24',
        imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.9,
        reviewCount: 67,
      },
      {
        title: 'Pho Bo Instant Noodle Premium',
        description: 'Authentic Vietnamese Pho Bo instant noodles with rich beef broth and traditional spices. Restaurant quality at home.',
        price: 12.99,
        stock: 234,
        categoryId: insertedCategories[10].id,
        sellerId: 'seed-seller-25',
        imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 456,
      },
      {
        title: 'Vietnamese Bamboo Lacquerware Set',
        description: 'Handcrafted bamboo bowls and chopsticks with traditional Vietnamese lacquer finish. Eco-friendly and elegant.',
        price: 89.99,
        stock: 34,
        categoryId: insertedCategories[10].id,
        sellerId: 'seed-seller-26',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 123,
      },
      {
        title: 'Nuoc Mam Fish Sauce Premium',
        description: 'Premium Vietnamese fish sauce from Phu Quoc Island. Essential ingredient for authentic Vietnamese cuisine.',
        price: 18.99,
        stock: 145,
        categoryId: insertedCategories[10].id,
        sellerId: 'seed-seller-27',
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 289,
      },

      // Office & Business
      {
        title: 'Ergonomic Office Chair Pro',
        description: 'Premium ergonomic office chair with lumbar support, adjustable height, and breathable mesh. Perfect for long work sessions.',
        price: 299.99,
        stock: 23,
        categoryId: insertedCategories[11].id,
        sellerId: 'seed-seller-28',
        imageUrl: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.5,
        reviewCount: 178,
      },
      {
        title: 'Wireless Presentation Remote',
        description: 'Professional wireless presenter with laser pointer, slide control, and 100ft range. Essential for business presentations.',
        price: 39.99,
        stock: 78,
        categoryId: insertedCategories[11].id,
        sellerId: 'seed-seller-29',
        imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.3,
        reviewCount: 234,
      },
      {
        title: 'Desk Organizer with Wireless Charger',
        description: 'Bamboo desk organizer with built-in wireless charging pad, pen holders, and compartments. Keep your workspace tidy.',
        price: 59.99,
        stock: 67,
        categoryId: insertedCategories[11].id,
        sellerId: 'seed-seller-30',
        imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.4,
        reviewCount: 156,
      },

      // Art & Crafts
      {
        title: 'Professional Watercolor Paint Set',
        description: 'Premium watercolor paint set with 36 colors, brushes, and mixing palette. Perfect for artists and beginners.',
        price: 79.99,
        stock: 45,
        categoryId: insertedCategories[12].id,
        sellerId: 'seed-seller-31',
        imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.6,
        reviewCount: 234,
      },
      {
        title: 'Handmade Ceramic Pottery Wheel',
        description: 'Electric pottery wheel for ceramics and clay work. Includes foot pedal and adjustable speed control.',
        price: 399.99,
        stock: 12,
        categoryId: insertedCategories[12].id,
        sellerId: 'seed-seller-32',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.7,
        reviewCount: 89,
      },
      {
        title: 'Embroidery Hoop Kit with Threads',
        description: 'Complete embroidery starter kit with hoops, needles, and colorful threads. Great for beginners and hobbyists.',
        price: 29.99,
        stock: 89,
        categoryId: insertedCategories[12].id,
        sellerId: 'seed-seller-33',
        imageUrl: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.5,
        reviewCount: 345,
      },

      // Additional trending electronics
      {
        title: 'Apple Vision Pro Mixed Reality',
        description: 'Revolutionary mixed reality headset with spatial computing and immersive experiences. The future of technology.',
        price: 3499.99,
        stock: 3,
        categoryId: insertedCategories[0].id,
        sellerId: 'seed-seller-34',
        imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.2,
        reviewCount: 23,
      },
      {
        title: 'Tesla Model S Key Fob',
        description: 'Official Tesla Model S key fob with advanced security features and sleek design. Premium automotive accessory.',
        price: 299.99,
        stock: 8,
        categoryId: insertedCategories[6].id,
        sellerId: 'seed-seller-35',
        imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=500&h=500&fit=crop',
        isActive: true,
        rating: 4.8,
        reviewCount: 45,
      },
    ];

    const insertedProducts = await db.insert(products).values(productData).returning();
    console.log(`✅ Created ${insertedProducts.length} products`);

    // Insert sample reviews
    const reviewData = [
      {
        productId: insertedProducts[0].id,
        userId: 'seed-user-1',
        rating: 5,
        comment: 'Tuyệt vời! Điện thoại chất lượng cao và camera thật sự ấn tượng. Đáng đồng tiền bát gạo.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[0].id,
        userId: 'seed-user-2',
        rating: 4,
        comment: 'Great phone overall, but the price is quite high. Camera quality is excellent though.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[1].id,
        userId: 'seed-user-3',
        rating: 5,
        comment: '정말 좋은 스마트폰입니다. S펜 기능이 매우 유용하고 화질도 선명해요.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[2].id,
        userId: 'seed-user-4',
        rating: 5,
        comment: 'Отличный ноутбук для работы. Быстрый, тихий и с отличным дисплеем.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[3].id,
        userId: 'seed-user-5',
        rating: 4,
        comment: 'Chất lượng âm thanh tuyệt vời và tính năng chống ồn rất hiệu quả.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[10].id,
        userId: 'seed-user-6',
        rating: 5,
        comment: 'This Instant Pot has changed my cooking game completely! So versatile and easy to use.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[16].id,
        userId: 'seed-user-7',
        rating: 5,
        comment: 'Cuốn sách thay đổi cách nhìn của tôi về tiền bạc. Rất khuyến khích mọi người đọc.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[19].id,
        userId: 'seed-user-8',
        rating: 4,
        comment: 'Dash cam chất lượng tốt, hình ảnh rõ nét cả ngày và đêm. Lắp đặt dễ dàng.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[23].id,
        userId: 'seed-user-9',
        rating: 5,
        comment: '아이들이 정말 좋아하는 레고 세트입니다. 조립 과정이 즐겁고 완성작도 멋져요.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[26].id,
        userId: 'seed-user-10',
        rating: 5,
        comment: 'Отличная автокормушка для кота. Теперь могу контролировать питание питомца даже на работе.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[29].id,
        userId: 'seed-user-11',
        rating: 5,
        comment: 'Cà phê Việt Nam ngon tuyệt vời! Hương vị đậm đà, thơm ngon. Sẽ đặt mua lại.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[30].id,
        userId: 'seed-user-12',
        rating: 4,
        comment: 'Beautiful chocolate gift set, perfect for special occasions. Great quality and presentation.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[32].id,
        userId: 'seed-user-13',
        rating: 5,
        comment: 'Áo dài rất đẹp và chất lượng tuyệt vời! Chất liệu lụa mềm mại, may tinh tế. Rất hài lòng với sản phẩm.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[33].id,
        userId: 'seed-user-14',
        rating: 5,
        comment: 'Phở bò ăn liền này ngon như phở thật! Nước dùng đậm đà, gia vị chuẩn vị. Sẽ mua lại.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[36].id,
        userId: 'seed-user-15',
        rating: 4,
        comment: 'Great ergonomic chair for long work sessions. Really helps with back support during remote work.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[39].id,
        userId: 'seed-user-16',
        rating: 5,
        comment: 'Excellent watercolor set! The colors are vibrant and the brushes are high quality. Perfect for art projects.',
        isVerifiedPurchase: true,
      },
      {
        productId: insertedProducts[41].id,
        userId: 'seed-user-17',
        rating: 4,
        comment: 'Apple Vision Pro는 정말 미래적인 기술이에요. 비싸지만 그만한 가치가 있습니다.',
        isVerifiedPurchase: true,
      },
    ];

    const insertedReviews = await db.insert(reviews).values(reviewData).returning();
    console.log(`✅ Created ${insertedReviews.length} reviews`);

    // Seed test accounts
    await seedTestAccounts();

    console.log('🎉 Database seeding completed successfully!');
    console.log(`Total: ${insertedCategories.length} categories, ${insertedProducts.length} products, ${insertedReviews.length} reviews`);

  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  }
}

// Run seeding if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase()
    .then(() => {
      console.log('Seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seeding failed:', error);
      process.exit(1);
    });
}