// Export Prisma types for shared use
export type {
  User,
  Category,
  Product,
  Review,
  ContentRating,
  CartItem,
  WishlistItem,
  Order,
  OrderItem,
  ChatRoom,
  ChatMessage,
  Property,
  Booking,
  PropertyReview,
  PropertyAvailability,
  RoomAvailability,
  Payment,
  Itinerary,
  ItineraryDay,
  ItineraryActivity,
  UserPreferences,
  UserInteraction,
  Recommendation,
  SimilarItem,
  TourDetail,
  TourSchedule,
  TicketDetail,
  TourBooking,
  Notification,
  Affiliate,
  AffiliateClick,
  AffiliateConversion,
  Payout,
  Discount,
  FormTemplate,
  FormField,
  ShippingAddress,
  UserPhone,
  RecentlyViewedProduct,
  SavedProduct,
  Session,
  Prisma
} from "@prisma/client";

// Re-export input types from storage-prisma
export type {
  UpsertUser,
  InsertCategory,
  InsertProduct,
  InsertReview,
  InsertCartItem,
  InsertWishlistItem,
  InsertOrder,
  InsertOrderItem,
  InsertChatRoom,
  InsertChatMessage,
  InsertProperty,
  InsertBooking,
  InsertPropertyReview,
  InsertPayment,
  InsertItinerary,
  InsertUserPreferences,
  InsertUserInteraction,
  InsertRecommendation,
  InsertSimilarItem,
  InsertTourDetail,
  InsertTourSchedule,
  InsertTicketDetail,
  InsertTourBooking,
  InsertNotification,
  InsertAffiliate,
  InsertAffiliateClick,
  InsertAffiliateConversion,
  InsertPayout,
  InsertDiscount
} from "../server/storage-prisma";
